export const GOAL_DESCRIPTION_MAX_LENGTH = 1500;
export const GOAL_AFORISM_MAX_LENGTH = 300;
export const GOAL_TIEMPO_ESTIMADO_MAX_LENGTH = 100;
export const GOAL_EJEMPLO_MAX_LENGTH = 1000;
export const GOAL_INDICADOR_EXITO_MAX_LENGTH = 1000;
export const GOAL_SURVEY_COMMENT_MAX_LENGTH = 1500;
